# Generated by Django 5.0.1 on 2024-02-12 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('display_name', models.CharField()),
                ('description', models.CharField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DiseaseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('display_name', models.CharField()),
                ('description', models.CharField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AnimalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('date', models.DateField()),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataportal.animal')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataportal.area')),
            ],
        ),
        migrations.CreateModel(
            name='CaseReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_count', models.IntegerField(default=0)),
                ('case_count_epi', models.IntegerField(default=0)),
                ('sex_female_count', models.IntegerField(default=0)),
                ('sex_male_count', models.IntegerField(default=0)),
                ('sex_unknown_count', models.IntegerField(default=0)),
                ('race_white_count', models.IntegerField(default=0)),
                ('race_black_count', models.IntegerField(default=0)),
                ('race_asian_count', models.IntegerField(default=0)),
                ('race_native_american_count', models.IntegerField(default=0)),
                ('race_other_count', models.IntegerField(default=0)),
                ('race_unknown_count', models.IntegerField(default=0)),
                ('ethnicity_hispanic_count', models.IntegerField(default=0)),
                ('ethnicity_non_hispanic_count', models.IntegerField(default=0)),
                ('ethnicity_unknown_count', models.IntegerField(default=0)),
                ('age_0_10_count', models.IntegerField(default=0)),
                ('age_11_20_count', models.IntegerField(default=0)),
                ('age_21_30_count', models.IntegerField(default=0)),
                ('age_31_40_count', models.IntegerField(default=0)),
                ('age_41_50_count', models.IntegerField(default=0)),
                ('age_51_60_count', models.IntegerField(default=0)),
                ('age_61_70_count', models.IntegerField(default=0)),
                ('age_71_80_count', models.IntegerField(default=0)),
                ('age_81_and_up_count', models.IntegerField(default=0)),
                ('age_unknown_count', models.IntegerField(default=0)),
                ('report_start_date', models.DateField()),
                ('report_end_date', models.DateField()),
                ('report_submission_date', models.DateField()),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dataportal.disease')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='disease',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dataportal.diseasecategory'),
        ),
        migrations.AddField(
            model_name='animal',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataportal.species'),
        ),
    ]
