# Generated by Django 5.0.1 on 2024-02-15 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataportal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalizedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inpatient_count', models.IntegerField()),
                ('under_investigation_count', models.IntegerField()),
                ('report_start_date', models.DateField()),
                ('report_end_date', models.DateField()),
                ('report_submission_date', models.DateField()),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataportal.disease')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
