# Generated by Django 5.0.1 on 2024-02-16 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataportal', '0002_hospitalizedreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeathReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('death_count', models.IntegerField()),
                ('report_start_date', models.DateField()),
                ('report_end_date', models.DateField()),
                ('report_submission_date', models.DateField()),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataportal.disease')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ICUReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icu_count', models.IntegerField()),
                ('report_start_date', models.DateField()),
                ('report_end_date', models.DateField()),
                ('report_submission_date', models.DateField()),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataportal.disease')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VaccinationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccination_count', models.IntegerField()),
                ('report_start_date', models.DateField()),
                ('report_end_date', models.DateField()),
                ('report_submission_date', models.DateField()),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataportal.disease')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
