# Generated by Django 5.0.1 on 2024-03-07 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataportal', '0003_deathreport_icureport_vaccinationreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='cdc_link',
            field=models.TextField(default='Link Me'),
        ),
        migrations.AddField(
            model_name='disease',
            name='mayo_link',
            field=models.TextField(default='Link Me'),
        ),
        migrations.AddField(
            model_name='disease',
            name='wiki_link',
            field=models.TextField(default='Link Me'),
        ),
    ]
