# Generated by Django 5.0.1 on 2024-02-12 20:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataportal', '0003_casereport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='casereport',
            old_name='end_date',
            new_name='report_end_date',
        ),
        migrations.RenameField(
            model_name='casereport',
            old_name='start_date',
            new_name='report_start_date',
        ),
        migrations.RenameField(
            model_name='casereport',
            old_name='sex_unknwon_count',
            new_name='sex_unknown_count',
        ),
        migrations.RemoveField(
            model_name='casereport',
            name='disease_category',
        ),
        migrations.AddField(
            model_name='casereport',
            name='report_submission_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
