# Generated by Django 5.0.1 on 2024-02-12 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataportal', '0004_rename_end_date_casereport_report_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disease',
            name='id',
        ),
        migrations.RemoveField(
            model_name='diseasecategory',
            name='id',
        ),
        migrations.AddField(
            model_name='disease',
            name='display_name',
            field=models.CharField(default='default'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diseasecategory',
            name='display_name',
            field=models.CharField(default='default'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='casereport',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='disease',
            name='name',
            field=models.CharField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='diseasecategory',
            name='name',
            field=models.CharField(primary_key=True, serialize=False),
        ),
    ]
