# Generated by Django 5.0.1 on 2024-02-12 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataportal', '0005_remove_disease_id_remove_diseasecategory_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casereport',
            name='disease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dataportal.disease'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dataportal.diseasecategory'),
        ),
    ]
