# Generated by Django 5.0.1 on 2024-03-07 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataportal', '0005_casereport_age_present_casereport_ethnicity_present_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccinationreport',
            name='disease',
        ),
        migrations.DeleteModel(
            name='ICUReport',
        ),
        migrations.DeleteModel(
            name='VaccinationReport',
        ),
    ]
